[package]
name = "reqwest-example"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
reqwest = "0.8.0"

[dependencies.kitsu_async]
features = ["reqwest-support"]
path = "../../"
